#!/bin/bash
docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
docker tag searchpe/searchpe-ui searchpe/searchpe-ui:$(git rev-parse --short HEAD);
docker tag searchpe/searchpe-ui-openshift searchpe/searchpe-ui-openshift:$(git rev-parse --short HEAD);
docker push searchpe/searchpe-ui
docker push searchpe/searchpe-ui-openshift
