#!/bin/bash
docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";

if [ -z "$TRAVIS_TAG" ]
then
  docker tag searchpe/searchpe-ui searchpe/searchpe-ui:$(git rev-parse --short HEAD);
  docker tag searchpe/searchpe-ui-openshift searchpe/searchpe-ui-openshift:$(git rev-parse --short HEAD);
else
  docker tag searchpe/searchpe-ui searchpe/searchpe-ui:$TRAVIS_TAG;
  docker tag searchpe/searchpe-ui-openshift searchpe/searchpe-ui-openshift:$TRAVIS_TAG;
fi

docker push searchpe/searchpe-ui
docker push searchpe/searchpe-ui-openshift
